import os
from dotenv import load_dotenv
from agent import run_research_agent

load_dotenv()

print("\n🚀 Instantiating Stable Multi-Agent Research System...")
print("==========================================================")

my_topic = "Latest advancements in solid state batteries"

try:
    # Trigger the agent pipeline natively
    final_report = run_research_agent(my_topic)
    
    print("\n==========================================================")
    print("📊 FINAL RESUME REPORT GENERATED BY SYSTEM:")
    print("==========================================================")
    print(final_report)
    print("==========================================================\n")

except Exception as e:
    print(f"\n❌ Pipeline stopped: {e}")
